### ISSUE TITLE
Why iterator isn't a param configurable?

### ISSUE THREAD

**Issue by ivolivares** [usabilla/api-js-node#29]
I don't understand the iterator parameter in the index.js file. There are no references in the documentation.
However, this parameter causes my API searches lose their search parameters after the first iteration. Especially when I want to request the last 10 (or n) feedbacks. Only the first iteration sends the correct parameters, then the default parameters are sent and not those that I sent.

```
src/index.js : constructor()

this.config = {
  method: 'GET',
  host: 'data.usabilla.com',
  iterator: true // THIS ... ¿WHY?
};
```

**Comment by spirosikmd** [comment]
Hi @ivolivares! Thank you very much for submitting this issue. `iterator` is used when response `hasMore` items. So then we fetch the next ones and so on and so forth. The cases that `hasMore` can be `true` is either by setting a `limit: 10` for example in your request parameters, or you have so many feedback items and data API returns by default a portion of them.

I tested and there is indeed a bug, which doesn't take into account the parameters for the subsequent requests.

**Comment by ivolivares** [comment]
@spirosikmd Please see the #34 PR, I need you publish the solution. Thanks :)
