### ISSUE TITLE
Issues connecting behind a corporate proxy

### ISSUE THREAD

**Issue by stefan-THD** [usabilla/api-js-node#35]
We are having issues getting this package to work with our enterprise proxy settings, is it possible to configure the https get method in resource.js to accept proxy settings?

**Comment by spirosikmd** [comment]
Hi @stefan-THD! Thank you for submitting this issue! Can you please provide a reproducible example? That would help a lot!

**Comment by stefan-THD** [comment]
Thanks spirosikmd, our company uses a proxy, which requires us to add additional options with the http request, but the default plugin doesn't allow to send in options to the http request.

```var Usabilla = require("usabilla-api");
var usabilla = new Usabilla(process.env.USABILLA_ACCESS_KEY, process.env.USABILLA_SECRET_KEY);
let buttonFeedbackQuery = {
  "id": "############",
  "params": {
    "limit": "500"
  }
};
function saveUsabillaInfo() {
    usabilla.websites.buttons.feedback.get(buttonFeedbackQuery).then(feedback => {
        console.log(JSON.stringify(feedback));
    }
}

saveUsabillaInfo();
```

Would give us a connection timeout error because it wasn't get through our proxy. We were able to remedy this by using the plugin to get the signatures and adding them to our own http request so that we could pass our own options. This is what we end up doing:

```
var Usabilla = require("usabilla-api");
var http = require('http');
var usabilla = new Usabilla(process.env.USABILLA_ACCESS_KEY, process.env.USABILLA_SECRET_KEY);

function saveUsabillaInfo() {
  var proxy = process.env.HTTP_PROXY;
  var proxySplit = proxy.split(':');
  var proxyServer = proxySplit[1].replace('//', '');
  var proxyPort = proxySplit[2];
  var date = new Date();
  date.setDate(date.getDate() - 120);
  date.setHours(0);
  date.setMinutes(0);
  date.setSeconds(0);

  var since = Math.round(date.getTime());

  let buttonFeedbackQuery = {
    "id": "############",
    "params": {
      "limit": "500"
    }
  };

  usabilla.websites.buttons.feedback.get(buttonFeedbackQuery);
  var signingFactory = usabilla.websites.buttons.signatureFactory;
  var signature = signingFactory.sign();
  var signedHeader = signature.headers;

  var options = {
    protocol: 'http:',
    host: proxyServer,
    port: proxyPort,
    path: '/live/websites/button/9c7cb92f1d37/feedback?since=' + since,
    headers: {
      'x-ub-api-client': signedHeader['x-ub-api-client'],
      'x-usbl-date': signedHeader['x-usbl-date'],
      host: 'data.usabilla.com',
      Authorization: signedHeader.Authorization
    }
  }


  http.get(options, function (response) {
    //PROCESS RESPONSE 
  });

}

saveUsabillaInfo();
```

**Comment by spirosikmd** [comment]
Thank you for the detailed information @stefan-THD! So if I understood well, you basically want to configure the `protocol`, `host`, and `port`? If you could do something like the following

```javascript
const usabilla = require('usabilla-api');

const proxy = process.env.HTTP_PROXY;
const proxySplit = proxy.split(':');
const proxyServer = proxySplit[1].replace('//', '');
const proxyPort = proxySplit[2];

usabilla.configure({
  protocol: 'http:',
  host: proxyServer,
  port: proxyPort,
});

usabilla.websites.buttons.feedback.get(/* query here */);
```

would this work for you?

**Comment by stefan-THD** [comment]
@spirosikmd Yes! Something along those lines should work well for us, as long that we can set those options.

**Comment by spirosikmd** [comment]
Hi @stefan-THD! You should be able to configure client in [v1.1.0](https://github.com/usabilla/api-js-node/releases/tag/v1.1.0)!

**Comment by stefan-THD** [comment]
We were able to try it out, apparently, even you set the protocol to http, `https` will still send it as https. Is there a way to use http instead of https?

**Comment by stefan-THD** [comment]
@spirosikmd Is there a way to use http instead of https yet?

**Comment by spirosikmd** [comment]
Hi @stefan-THD! It is true, by default the `https` package uses the https protocol. I haven't looked at it yet. I guess it is possible to use the `http` package, when someone specifies the http protocol through the config.

**Comment by stefan-THD** [comment]
Thanks so much! We will check it out.
